### ISSUE TITLE
Error when queries contain GatsbyImageSharp fragments

### ISSUE THREAD

**Issue by hazem3500** [daugsbi/gatsby-plugin-codegen#1]
On running `gatsby develop` the message `warn ⚠️  It looks like there are 0 files associated with this Apollo Project. This may be because you don't have any files yet`

then when I save a file which has a query with a GastbyImageSharp fragment it gives me this error 

`.../Component.tsx: Unknown fragment "GatsbyImageSharpFluid".`
`ToolError: Validation of GraphQL query document failed`

**Comment by daugsbi** [comment]
The warning looks fine, when there are no files with queries in it. 

The "GatsbyImageSharpFluid" fragment is defined in the package "gatsby-transformer-sharp" and included by this plugin.

Have you installed it?

`npm install --save gatsby-transformer-sharp`

**Comment by hazem3500** [comment]
Yes I have installed it as a dependency, the problem is when I run it on another machine it works perfectly fine.

**Comment by hazem3500** [comment]
both machines have the same node version, but one gives the `warn ⚠️ It looks like there are 0 files associated...` warning and crashes when saving a file with the GatsbyImageSharp fragment and the other works fine, I am on `"gatsby-transformer-sharp": "^2.2.23"` and `"gatsby-plugin-codegen": "^1.0.7"`, my gatsby config is the same as the default one
```
    {
         resolve: 'gatsby-plugin-codegen',
         options: {},
    },
```

`apollo.config.js`
```
module.exports = {
  client: {
    addTypename: false,
    excludes: [],
    includes: ["./src/**/*.tsx","./src/**/*.ts","./node_modules/gatsby-source-contentful/src/*.js","./node_modules/gatsby-transformer-sharp/src/*.js","./node_modules/gatsby-image/src/*.js"],
    service: {
      name: "gatsbySchema",
      localSchemaFile: "./schema.json"
    },
    tagName: "graphql"
  }
}
```

**Comment by hazem3500** [comment]
I found the issue 😅, the machine that didn't work was in a folder that had `%20` in its name which seemed to mess up the included paths in apollo config, so after removing the `%20` from the folder name it worked 🎉
