### ISSUE TITLE
Fails to generate query files with typescript target

### ISSUE THREAD

**Issue by insuusvenerati** [daugsbi/gatsby-plugin-codegen#11]
I'm getting an error in a new `gatsby new` created project: 

```
warn [gatsby-plugin-codegen] could not generate types from queries - Syntax error in /node_modules/gatsby-transformer-sharp/src/customize-schema.js: Syntax    
Error: Unexpected )
```
apollo.config.js is created successfully.

gatsby-config.js only additionally has 
```js
    `gatsby-plugin-typescript`,
    `gatsby-plugin-codegen`,
```
added.

The issue is resolved with the config set like: 
```js
{
      resolve: "gatsby-plugin-codegen",
      options: {
        includes: [
          "./src/**/*.tsx",
          "./src/**/*.ts",
          "./plugins/**/*.js",
          "./node_modules/gatsby-source-contentful/src/*.js",
          "./node_modules/gatsby-source-datocms/fragments/*.js",
          "./node_modules/gatsby-image/src/*.js",
        ],
        excludes: ["./node_modules/gatsby-transformer-sharp/src/*.js"],
      },
    },
```
Additionally, removing a directory from `includes` doesn't seem to make it ignore that directory. Only after adding it to excludes does it finally ignore it.

**Comment by daugsbi** [comment]
Hi @insuusvenerati 
Thx for your detailed issue report. I have checked the default values and limited them now to include the fragment files only. Can you check, if version 1.2 resolved your issue?

Yes, that is correct. The defined includes in gatsby-config are additionally to the default ones set by gatsby-plugin-codegen. The reason for this descision is to not break something, if you only add/define an additional fragment of a plugin without redefining all default ones.
But of course, they should not include something breaking either :)
