### ISSUE TITLE
Gatsby 3 support

### ISSUE THREAD

**Issue by skoch** [daugsbi/gatsby-plugin-codegen#17]
Any plans to update the `gatsby` `peerDependency` to `^3.0.0`?

**Comment by stefanpl** [comment]
Couldn't make this plugin work with gatsby 3 … bummer :\ 

[gatsby-plugin-typegen](https://github.com/cometkim/gatsby-plugin-typegen) might be a valid alternative, I'll check it out.

**Comment by daugsbi** [comment]
Now it should work with Gatsby v3. Please check out the version 3.0.0 of the plugin

**Comment by graysonhicks** [comment]
Can confirm 3.0+ works on v3, this issue can be closed.  Thanks @daugsbi !

**Comment by skoch** [comment]
Thanks for confirming @graysonhicks !
