### ISSUE TITLE
nulls

### ISSUE THREAD

**Issue by omerman** [daugsbi/gatsby-plugin-codegen#4]
It seems like every type is generated as `Type | null`.
is there a way to avoid it?

Thanks

**Comment by daugsbi** [comment]
Hi @omerman 
Yes that bothers me too. If you check your gatsby graphql schema, you will find a lot of definitions which are declared nullable. For example:

`
type BlogPost {
  title: String
}
`

If the BlogPosts title is required it should be represented in the schema as well.

`
type BlogPost {
  title: String!
}
`

I would consider the following options:
- You can fix the default behavior of gatsby by using schema customization (https://www.gatsbyjs.org/blog/2019-03-04-new-schema-customization/). Just redefine your required fields with a question mark.

- Improve the schema of your source plugins by contribution.

- Set the fields to required in your cms (not working with contentful yet).

- Use TypeScripts Optional Chaining (> 3.7).
