### ISSUE TITLE
No error message when types aren't generated because of anonymous GraphQL queries

### ISSUE THREAD

**Issue by JagdCake** [daugsbi/gatsby-plugin-codegen#7]
I'm working on a TypeScript starter using `gatsby-starter-default` as a base. I followed the steps in [this blog post](https://www.gatsbyjs.org/blog/2020-01-23-why-typescript-chose-gatsby/#typescript-support) to get TypeScript support, however on the last step — generating the types using this plugin — the types weren't being generated.

Running `npm run develop` displayed success messages:
```
success [gatsby-plugin-codegen] saved localSchemaFile: ./schema.json
success [gatsby-plugin-codegen] saved apollo config:
success [gatsby-plugin-codegen] types for typescript generated
```
Both the schema and config files showed up, but the `__generated__` directories didn't.

I tried `node_modules/apollo/bin/run client:codegen -c apollo.config.js --target=typescript --outputFlat gql-types.d.ts` and I got an error: `Apollo does not support anonymous operations`, which led me to [this comment](https://github.com/apollographql/apollo-tooling/issues/184#issuecomment-317810795). Naming the queries fixed the problem.

**Comment by daugsbi** [comment]
Yes, all queries need a unique name (compare with https://github.com/apollographql/apollo-tooling/issues/670). 

I've tried to reproduce the incorrect success message. When I do not name one query it shows me the following
![query_naming_apollo-codegen](https://user-images.githubusercontent.com/5528706/73436867-98008300-434b-11ea-8839-85354bbfb9ed.png)

Do you have any additional information or a repository to share?

**Comment by JagdCake** [comment]
`git clone -b gql-types https://github.com/JagdCake/gatsby-typescript-tailwind-starter.git`. The query in `src/components/seo.tsx` is anonymous and when I run `npm run develop` there is no error, `git status` shows only the apollo config and schema.json.

**Comment by daugsbi** [comment]
Thanks for the reproduction :+1:  
As a temporary workaround set the plugin option watch to false.

I need to check if it's possible to keep the file watchers of apollo and still be compatible with the newest version of gatsby-cli (>=2.8.28).

Please keep the issue open

**Comment by daugsbi** [comment]
I've changed the default option watch to false. For people still wanted to use the watch mode the best solution is to set it the following way:
process.env.NODE_ENV === "development" ? true : false

As a result you get the error message during build time instead of development.
